# Sidebar navigation

- label: Home
  link: "/"
- label: Website Releases
  link: "/releases"
- label: How to Join
  link: "/how-to-join"
- label: The Kusama Fratority
  link: "/the-fratority"
- label: External Links
  items:
    - label: Society Rules
      link: https://polkascan.io/kusama/transaction/0x948d3a4378914341dc7af9220a4c73acb2b3f72a70f14ee8089799da16d94c17
    - label: Motion 186
      link: https://kusama.polkassembly.io/motion/186
    - label: The Third Generation
      link: https://www.youtube.com/watch?v=-JfQ2vCipWU&t=4s
    - label: Branding Drive
      link: https://drive.google.com/drive/u/1/folders/1ReG63yRvPgIRRyryDTbrACHELcZoMkA3
    - label: Code Repository
      link: https://github.com/KappaSigmaMu
    - label: Trello
      link: https://trello.com/b/aqOYaoD0/brand-and-website
